[package]
name = "sm-pipe"
version = "0.1.0"
edition = "2024"
authors = ["adamanteye <ada@adamanteye.cc>"]
license = "MIT"

[features]
telegram = ["dep:frankenstein"]

[dependencies]
frankenstein = { version = "0.39.2", features = [
  "trait-async",
], optional = true }
